# Generated by Django 5.2.4 on 2025-07-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
    ]
