# Generated by Django 5.2.4 on 2025-07-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_education_field_of_study'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name_plural': 'Expertise'},
        ),
    ]
