# Generated by Django 5.2.4 on 2025-07-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_expertise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name_plural': 'Intro'},
        ),
    ]
