# Generated by Django 5.2.4 on 2025-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_intro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('certificateImg_small', models.ImageField(upload_to='certificates/small_img/')),
                ('certificateImg_big', models.ImageField(upload_to='certificates/big_img/')),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('projectImg_small', models.ImageField(upload_to='projects/small_img/')),
                ('projectImg_big', models.ImageField(upload_to='projects/big_img/')),
            ],
        ),
        migrations.AlterField(
            model_name='intro',
            name='profile_pic',
            field=models.ImageField(upload_to='personal/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='resume',
            field=models.FileField(upload_to='personal/'),
        ),
    ]
