# Generated by Django 5.2.4 on 2025-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_certificates_project_alter_intro_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectImg_big',
            field=models.ImageField(blank=True, null=True, upload_to='projects/big_img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImg_small',
            field=models.ImageField(blank=True, null=True, upload_to='projects/small_img/'),
        ),
    ]
