# Generated by Django 5.2.4 on 2025-07-17 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_project_projectimg_big_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 17, 9, 23, 39, 886479, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
