# Generated by Django 5.2.4 on 2025-07-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project_projectimg_relative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectImg_relative',
        ),
    ]
