# Generated by Django 5.2.4 on 2025-07-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_project_projectimg_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectImg_relative',
            field=models.ImageField(null=True, upload_to='projects/relative_img/'),
        ),
    ]
