# Generated by Django 5.2.4 on 2025-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_project_projectimg_relative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': '6. Certificates', 'verbose_name_plural': '6. Certificates'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': '4. Education', 'verbose_name_plural': '4. Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': '3. Experience', 'verbose_name_plural': '3. Experience'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': '2. Expertise', 'verbose_name_plural': '2. Expertise'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': '1. Intro', 'verbose_name_plural': '1. Intro'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at'], 'verbose_name': '5. Project', 'verbose_name_plural': '5. Projects'},
        ),
        migrations.AddField(
            model_name='certificates',
            name='company_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='certificates/logo/'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='certificateImg_big',
            field=models.ImageField(null=True, upload_to='certificates/big_img/'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='certificateImg_small',
            field=models.ImageField(null=True, upload_to='certificates/small_img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImg_big',
            field=models.ImageField(upload_to='projects/big_img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImg_relative',
            field=models.ImageField(upload_to='projects/relative_img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectImg_small',
            field=models.ImageField(upload_to='projects/small_img/'),
        ),
    ]
