# Generated by Django 5.2.4 on 2025-07-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_certificates_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
