# Generated by Django 5.2.4 on 2025-07-19 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_certificates_certificate_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'ordering': ['created_at'], 'verbose_name': '6. Certificates', 'verbose_name_plural': '6. Certificates'},
        ),
        migrations.AddField(
            model_name='certificates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
