# Generated by Django 5.2.4 on 2025-07-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_certificates_options_certificates_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='company_location',
            new_name='type',
        ),
    ]
