# Generated by Django 5.2.4 on 2025-07-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_company_location_certificates_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='certificateImg_small',
        ),
    ]
